server:
  port: 800

bootstrapServers: "oci:9092,oci:9093,oci:9094"

spring:
  datasource:
    url: jdbc:mysql://oci:3306/kafka_toy?autoReconnect=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kafka_toy
    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        type: debug
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace